<?php

return [
    'materials_categories' => [
        ['name' => 'Cement', 'description' => 'Portland Cement, Masonry Cement'],
        ['name' => 'Sand', 'description' => 'Fine Sand, Washed Sand'],
        ['name' => 'Gravel', 'description' => '3/4 Gravel, G1, G2'],
        ['name' => 'Steel Bars', 'description' => '10mm, 12mm, 16mm Rebars'],
        ['name' => 'Tie Wire', 'description' => 'GI Tie Wire'],
        ['name' => 'Lumber', 'description' => 'Coco Lumber, Mahogany'],
        ['name' => 'Plywood', 'description' => 'Marine Plywood, Ordinary Plywood'],
        ['name' => 'Roofing', 'description' => 'Long Span Roof, Rib Type'],
        ['name' => 'Hollow Blocks', 'description' => '4", 5", 6" CHB'],
        ['name' => 'Bricks', 'description' => 'Clay Bricks'],
        ['name' => 'Tiles', 'description' => 'Floor Tiles, Wall Tiles'],
        ['name' => 'Paint', 'description' => 'Primer, Latex, Enamel'],
        ['name' => 'Plumbing', 'description' => 'PVC Pipe, Elbow, Tee, Faucet'],
        ['name' => 'Electrical', 'description' => 'Wires, Breakers, Switches, Outlets'],
        ['name' => 'Doors', 'description' => 'Wooden Door, Steel Door'],
        ['name' => 'Windows', 'description' => 'Aluminum Window, Glass Window'],
        ['name' => 'Ceiling', 'description' => 'Gypsum Board, Ceiling Joist'],
        ['name' => 'Fasteners', 'description' => 'Nails, Screws, Bolts'],
        ['name' => 'Adhesives', 'description' => 'Rugby, Epoxy, Sealant'],
        ['name' => 'Hardware Tools', 'description' => 'Hammer, Trowel, Grinder'],
        ['name' => 'Safety Equipment', 'description' => 'Helmet, Gloves, Safety Vest'],
        ['name' => 'Miscellaneous', 'description' => 'Other construction supplies'],
    ],
    'daily_expense_categories' => [
        'Labor',
        'Transportation',
        'Fuel',
        'Equipment Rental',
        'Food Allowance',
        'Accommodation',
        'Communication',
        'Utility Bills',
        'Repairs & Maintenance',
        'Permit & Fees',
        'Office Supplies',
        'Miscellaneous',
    ],
    'supplier_categories' => [
        'Cement Supplier',
        'Steel Supplier',
        'Lumber Supplier',
        'Plumbing Supplier',
        'Electrical Supplier',
        'Paint Supplier',
        'Roofing Supplier',
        'Hardware Store',
        'Equipment Rental',
        'General Supplier',
    ],
    'user_roles' => [
        'Administrator',
        'Owner',
        'Staff',
        'Viewer',
    ],
    'project_statuses' => [
        'Planning',
        'Ongoing',
        'Completed',
        'On Hold',
        'Cancelled',
    ],
    'payment_statuses' => [
        'Paid',
        'Unpaid',
        'Partially Paid',
        'Cancelled',
    ],
    'unit_categories' => [
        'Piece (pc)',
        'Box',
        'Bag',
        'Sack',
        'Kilogram (kg)',
        'Meter (m)',
        'Square Meter (m2)',
        'Cubic Meter (m3)',
        'Roll',
        'Bundle',
        'Gallon',
        'Liter',
        'Drum',
        'Sheet',
        'Set',
    ],
    'transaction_types' => [
        'Material Purchase',
        'Daily Expense',
        'Material Return',
        'Material Adjustment',
        'Material Transfer',
        'Budget Allocation',
    ],
    'report_types' => [
        'Daily Report',
        'Weekly Report',
        'Monthly Report',
        'Materials Report',
        'Expenses Report',
        'Supplier Report',
        'Project Cost Report',
        'Inventory Report',
    ],
];
